In [1]:
import numpy as np 
import math


Array creation

In [3]:
#arrays are displayed as a list, or a list of lists and can be created through lists as well
#when creating an array, we pass in a list as an argument in numpy array.
a = np.array([1, 2, 3])
print(a)
print(a.ndim)

[1 2 3]
1


In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
2
